In [3]:
!pip install tensorflow-gpu

In [4]:
import tensorflow as tf
print(tf.__version__)

2.10.0


In [5]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [6]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [7]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [8]:
### Vocabulary size
voc_size=500

One hot representation


In [9]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[207, 129, 345, 426], [207, 129, 345, 122], [207, 325, 345, 23], [295, 406, 205, 420, 70], [295, 406, 205, 420, 43], [457, 207, 150, 345, 348], [214, 348, 253, 420]]


## WORD EMBEDDING

In [10]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [11]:
import numpy as np

In [12]:
## pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 207 129 345 426]
 [  0   0   0   0 207 129 345 122]
 [  0   0   0   0 207 325 345  23]
 [  0   0   0 295 406 205 420  70]
 [  0   0   0 295 406 205 420  43]
 [  0   0   0 457 207 150 345 348]
 [  0   0   0   0 214 348 253 420]]


In [13]:
## 10 feature dimesnions
dim=10

In [14]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [15]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             5000      
                                                                 
Total params: 5,000
Trainable params: 5,000
Non-trainable params: 0
_________________________________________________________________


In [16]:
##'the glass of milk',
embedded_docs[0]

array([  0,   0,   0,   0, 207, 129, 345, 426])

In [17]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 238ms/step


array([[-0.02663502, -0.04278461,  0.04892448,  0.00010413, -0.02244438,
         0.04565103,  0.04187149,  0.01979811, -0.03356123,  0.01124484],
       [-0.02663502, -0.04278461,  0.04892448,  0.00010413, -0.02244438,
         0.04565103,  0.04187149,  0.01979811, -0.03356123,  0.01124484],
       [-0.02663502, -0.04278461,  0.04892448,  0.00010413, -0.02244438,
         0.04565103,  0.04187149,  0.01979811, -0.03356123,  0.01124484],
       [-0.02663502, -0.04278461,  0.04892448,  0.00010413, -0.02244438,
         0.04565103,  0.04187149,  0.01979811, -0.03356123,  0.01124484],
       [-0.04399748, -0.0019868 ,  0.02140078,  0.04470937, -0.04319723,
         0.03349524, -0.02846998,  0.03647855,  0.00864259,  0.03549374],
       [ 0.00196953,  0.04008019,  0.03637997, -0.04244492, -0.0475329 ,
         0.02088132, -0.04133569, -0.04103713, -0.03902351, -0.04525421],
       [ 0.01668138, -0.00842345,  0.01482159, -0.04834322, -0.03314646,
        -0.0454872 ,  0.01464976, -0.02052561

In [18]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 94ms/step
[[[-0.02663502 -0.04278461  0.04892448  0.00010413 -0.02244438
    0.04565103  0.04187149  0.01979811 -0.03356123  0.01124484]
  [-0.02663502 -0.04278461  0.04892448  0.00010413 -0.02244438
    0.04565103  0.04187149  0.01979811 -0.03356123  0.01124484]
  [-0.02663502 -0.04278461  0.04892448  0.00010413 -0.02244438
    0.04565103  0.04187149  0.01979811 -0.03356123  0.01124484]
  [-0.02663502 -0.04278461  0.04892448  0.00010413 -0.02244438
    0.04565103  0.04187149  0.01979811 -0.03356123  0.01124484]
  [-0.04399748 -0.0019868   0.02140078  0.04470937 -0.04319723
    0.03349524 -0.02846998  0.03647855  0.00864259  0.03549374]
  [ 0.00196953  0.04008019  0.03637997 -0.04244492 -0.0475329
    0.02088132 -0.04133569 -0.04103713 -0.03902351 -0.04525421]
  [ 0.01668138 -0.00842345  0.01482159 -0.04834322 -0.03314646
   -0.0454872   0.01464976 -0.02052561  0.042796    0.03080383]
  [-0.0166008   0.04186703 -0.01624123  0.04187683  0.030668

In [19]:
embedded_docs[0]

array([  0,   0,   0,   0, 207, 129, 345, 426])

In [20]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 47ms/step
[[-0.02663502 -0.04278461  0.04892448  0.00010413 -0.02244438  0.04565103
   0.04187149  0.01979811 -0.03356123  0.01124484]
 [-0.02663502 -0.04278461  0.04892448  0.00010413 -0.02244438  0.04565103
   0.04187149  0.01979811 -0.03356123  0.01124484]
 [-0.02663502 -0.04278461  0.04892448  0.00010413 -0.02244438  0.04565103
   0.04187149  0.01979811 -0.03356123  0.01124484]
 [-0.02663502 -0.04278461  0.04892448  0.00010413 -0.02244438  0.04565103
   0.04187149  0.01979811 -0.03356123  0.01124484]
 [-0.04399748 -0.0019868   0.02140078  0.04470937 -0.04319723  0.03349524
  -0.02846998  0.03647855  0.00864259  0.03549374]
 [ 0.00196953  0.04008019  0.03637997 -0.04244492 -0.0475329   0.02088132
  -0.04133569 -0.04103713 -0.03902351 -0.04525421]
 [ 0.01668138 -0.00842345  0.01482159 -0.04834322 -0.03314646 -0.0454872
   0.01464976 -0.02052561  0.042796    0.03080383]
 [-0.0166008   0.04186703 -0.01624123  0.04187683  0.03066821 -0.04787226
